/*
 * Copyright 2010 Casalinuovo Dario
 * All rights reserved. Distributed under the terms of the MIT license.
 */

#define VCARD_ADDRESS              "ADR"
#define VCARD_AGENT                "AGENT"
#define VCARD_BIRTHDAY             "BDAY"
#define VCARD_CATEGORIES           "CATEGORIES"
#define VCARD_CLASS                "CLASS"
#define VCARD_DELIVERY_LABEL       "LABEL"
#define VCARD_EMAIL                "EMAIL"
#define VCARD_FORMATTED_NAME       "FN"
#define VCARD_REVISION             "REV"
#define VCARD_ROLE                 "ROLE"
#define VCARD_SORT_STRING          "SORT-STRING"
#define VCARD_SOUND                "SOUND"
#define VCARD_TELEPHONE            "TEL"
#define VCARD_TIME_ZONE            "TZ"
#define VCARD_TITLE                "TITLE"
#define VCARD_URL                  "URL"
#define VCARD_GEOGRAPHIC_POSITION  "GEO"
#define VCARD_KEY                  "KEY"
#define VCARD_LOGO                 "LOGO"
#define VCARD_MAILER               "MAILER"
#define VCARD_NAME                 "N"
#define VCARD_NICKNAME             "NICKNAME"
#define VCARD_NOTE                 "NOTE"
#define VCARD_ORGANIZATION         "ORG"
#define VCARD_PHOTO                "PHOTO"
#define VCARD_PRODUCT_IDENTIFIER   "PRODID"
#define VCARD_VERSION              "VERSION"
